# Generated by Django 5.1.6 on 2025-02-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location_city', models.CharField(max_length=200)),
                ('location_state_province', models.CharField(max_length=200)),
                ('location_country', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('category', models.CharField(choices=[('animal', 'Animal'), ('food', 'Food'), ('trinket', 'Trinket'), ('other', 'Other')], default='other', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='thingsImages/')),
                ('is_draft', models.BooleanField(default=False)),
            ],
        ),
    ]
