# Generated by Django 5.1.6 on 2025-02-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldslargestthings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
